# SPDX-FileCopyrightText: 2022 Yu Zhu <891085309@qq.com>
#
# SPDX-License-Identifier: MIT

name: Publish Package

on:
    push:
        tag:
            - "v*"

jobs:
    publish:
        # prevents this action from running on forks
        if: github.repository == 'ZhUyU1997/MEUI'
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
              with:
                  version: 7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
                  cache: "pnpm"
            - name: Install Packages
              run: |
                  sudo apt install gcc make libxkbcommon-dev
            - run: pnpm install
            - run: pnpm -F @meui/core -F @meui/spring -F @meui/preact -F @meui/components run build
            - name: Publish package
              run: pnpm run ci-publish ${{ github.ref_name }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
